# Generated by Django 5.1.1 on 2025-04-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_assigned', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='case',
            name='counselor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='case',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.profile'),
        ),
    ]
