# Generated by Django 5.2 on 2025-04-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointment_counselor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('academic', 'Academic Concerns'), ('personal', 'Personal Issues'), ('career', 'Career Planning'), ('mental_health', 'Mental Health Support'), ('other', 'Other')], max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', '9:00 AM - 12:00 PM'), ('afternoon', '1:00 PM - 4:00 PM'), ('evening', '5:00 PM - 7:00 PM')], max_length=20)),
                ('concern_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.CharField(blank=True, choices=[('morning', '9:00 AM - 12:00 PM'), ('afternoon', '1:00 PM - 4:00 PM'), ('evening', '5:00 PM - 7:00 PM')], max_length=20, null=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='app.profile')),
                ('preferred_counselor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_sessions', to='app.profile')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_sessions', to='app.profile')),
            ],
        ),
    ]
