# Generated by Django 5.1.6 on 2025-06-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_casestatus_caseupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity_level', models.IntegerField(choices=[(1, 'Minor'), (2, 'Moderate'), (3, 'Major'), (4, 'Severe')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_level', models.IntegerField(choices=[(1, '1st Hearing'), (2, '2nd Hearing'), (3, '3rd Hearing'), (4, '4th Hearing')])),
                ('scheduled_date', models.DateTimeField()),
                ('hearing_notes', models.TextField(blank=True)),
                ('student_statement', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('warning', 'Warning'), ('probation', 'Probation'), ('suspension', 'Suspension'), ('community_service', 'Community Service'), ('counseling_required', 'Mandatory Counseling'), ('dismissed', 'Case Dismissed'), ('escalate', 'Escalate to Next Level')], max_length=30)),
                ('decision_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_hearings', to=settings.AUTH_USER_MODEL)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_hearings', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_reason', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='appeals/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('review_decision', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to='app.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app.profile')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app.hearing')),
            ],
        ),
        migrations.CreateModel(
            name='HearingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.hearing')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('current_hearing_level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('appealed', 'Appealed'), ('dismissed', 'Dismissed')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='app.case')),
                ('offense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.offensetype')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_evaluations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='hearing',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='app.studentevaluation'),
        ),
        migrations.CreateModel(
            name='EvaluationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='app.studentevaluation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('incident_report', 'Incident Report'), ('witness_statement', 'Witness Statement'), ('evidence', 'Evidence'), ('medical_report', 'Medical Report'), ('character_reference', 'Character Reference'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='evaluation_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.studentevaluation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hearing',
            unique_together={('evaluation', 'hearing_level')},
        ),
    ]
