# Generated by Django 5.1.6 on 2025-06-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_evaluationdocument_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('report_data', models.JSONField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_for_session', models.CharField(choices=[('tardiness', 'Tardiness'), ('absence', 'Unexcused Absence'), ('misconduct', 'Academic Misconduct'), ('disruption', 'Classroom Disruption'), ('bullying', 'Bullying/Harassment'), ('violation', 'Code of Conduct Violation'), ('substance', 'Substance-related Issue'), ('other', 'Other')], max_length=20)),
                ('hearing_frequency', models.CharField(choices=[('1st', '1st Hearing'), ('2nd', '2nd Hearing'), ('3rd', '3rd Hearing'), ('4th', '4th Hearing (Final)')], max_length=3)),
                ('detailed_assessment', models.TextField()),
                ('severity_level', models.CharField(choices=[('minor', 'Minor Offense'), ('major', 'Major Offense'), ('severe', 'Severe Offense')], max_length=10)),
                ('follow_up_required', models.CharField(choices=[('none', 'No Follow-up Needed'), ('monitoring', 'Behavioral Monitoring'), ('counseling', 'Additional Counseling'), ('parent', 'Parent Conference'), ('disciplinary', 'Disciplinary Action')], default='none', max_length=15)),
                ('is_draft', models.BooleanField(default=False)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_evaluations', to='app.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
