# Generated by Django 5.1.6 on 2025-06-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
