# Generated by Django 5.1.6 on 2025-06-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidancesession',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='guidancesession',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='guidancesession',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='guidancesession',
            name='scheduled_time',
        ),
    ]
