# Generated by Django 5.1.6 on 2025-06-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_guidancesession_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='student_course',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student_name',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student_section',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student_year',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='guidancesession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.profile'),
        ),
    ]
