# Generated by Django 5.1.6 on 2025-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_guidancesession_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='offense_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='offense_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='witnesses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
