# Generated by Django 5.1.6 on 2025-06-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_guidancesession_case_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
