# Generated by Django 5.1.6 on 2025-06-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_case_scheduled_date_case_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_statuses', to='app.profile'),
        ),
    ]
