# Generated by Django 5.1.6 on 2025-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_case_case_number_alter_casestatus_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='counselor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
