# Generated by Django 5.1.6 on 2025-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_guidancesession_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='sessions',
            field=models.ManyToManyField(related_name='cases', to='app.guidancesession'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
