from django import views
from django.urls import path
from .views import calendar_events, guidance_request_success, home, about, signup, verify_email, student_dashboard, student_cases, create_comment, contact, login_view, dashboard, schedule_guidance_session, check_case_status, view_case_details, update_case_status, case_history, case_reports, case_detail, student_cases_dashboard, student_case, student_list, analytics_dashboard, evaluation, submit_evaluation, save_evaluation_draft, evaluation_list, evaluation_detail, get_recent_evaluations, generate_evaluation_report, student_settings, update_session_status, set_session_schedule, create_session, verify_email, session_created, update_session_time, edit_case, cancel_case, student_cases_only, student_sessions_only, case_detail_view, session_detail_view, verify_otp, resend_otp, counselor_create_session, api_get_students, api_get_profiles, api_get_counselors, api_get_active_cases, counselor_schedule_hearing, counselor_hearing_detail, counselor_hearings_list, counselor_hearing_upload_evidence, counselor_hearing_post_decision, check_new_notifications, counselor_dashboard, counselor_sessions, counselor_session_detail, counselor_approve_session, counselor_complete_session, counselor_reject_session, counselor_cases, counselor_case_detail, counselor_create_case, counselor_students, counselor_student_profile, counselor_calendar, counselor_reports, counselor_settings, counselor_update_session_title, counselor_reports_export, view_all_notifications, mark_notification_read, mark_all_notifications_read, get_notifications, counselor_reschedule_session, counselor_link_session_to_case
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('dashboard/', dashboard, name='dashboard'),
    path('student_case/', student_case, name='student_case'),
    path('student_list/', student_list, name='student_list'),
    path('create_session/', create_session, name='create_session'),
    path('session_created/', session_created, name='session_created'),
    path('about/', about, name='about'),
    path('case-history/', case_history, name='case_history'),
    path('case-reports/', case_reports, name='case-reports'),
    path('case-detail/', case_detail, name='case-detail'),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('signup/', signup, name='signup'),
    path('verify-otp/<int:user_id>/', verify_otp, name='verify_otp'),
    path('resend-otp/<int:user_id>/', resend_otp, name='resend_otp'),
    path('student/dashboard/', student_dashboard, name='student_dashboard'),
    path('student/cases/old/', student_cases, name='student_cases'),
    path('student/cases/dashboard', student_cases_dashboard, name='student_cases_dashboard'),
    path('case/<int:case_id>/comment/', create_comment, name='create_comment'),
    path('case/<int:case_id>/', view_case_details, name='view_case_details'),
    path('student/session/', schedule_guidance_session, name='schedule_session'),
    path('student/status/', check_case_status, name='check_status'),
    path('guidance-request-success/', guidance_request_success, name='guidance_request_success'),
    path('case/<int:case_id>/update/', update_case_status, name='update_case_status'),
    path('analytics/', analytics_dashboard, name='analytics'),
    path('update-se     ssion-status/<int:session_id>/', update_session_status, name='update_session_status'),
    path('evaluations/', evaluation, name='evaluation'),
    path('evaluations/submit/', submit_evaluation, name='submit_evaluation'),
    path('evaluations/save-draft/', save_evaluation_draft, name='save_evaluation_draft'),
    path('evaluations/list/', evaluation_list, name='evaluation_list'),
    path('evaluations/<int:evaluation_id>/', evaluation_detail, name='evaluation_detail'),
    path('evaluations/recent/', get_recent_evaluations, name='get_recent_evaluations'),
    path('evaluations/generate-report/', generate_evaluation_report, name='generate_evaluation_report'),
    path('student/settings/', student_settings, name='student_settings'),
    path('session/<int:session_id>/setx-schedule/', set_session_schedule, name='set_session_schedule'),
    path('api/calendar-events/', calendar_events, name='calendar_events'),
    path('session/<int:session_id>/update-time/', update_session_time, name='update_session_time'),
    path('session/<int:session_id>/view/', view_case_details, name='view_case_details'),
    path('update_case_status/<int:case_id>/', update_case_status, name='update_case_status'),
    

    path('case/edit/', edit_case, name='edit_case'),
    path('case/cancel/', cancel_case, name='cancel_case'),
    path('student/cases/', student_cases_only, name='student_cases_only'),
    path('student/sessions/', student_sessions_only, name='student_sessions_only'),
    path('case/<int:case_id>/detail/', case_detail_view, name='case_detail_view'),
    path('session/<int:session_id>/detail/', session_detail_view, name='session_detail_view'),
    # Counselor Dashboard URLs
    path('counselor/dashboard/', counselor_dashboard, name='counselor_dashboard'),
    path('counselor/sessions/', counselor_sessions, name='counselor_sessions'),
    path('counselor/session/<int:session_id>/', counselor_session_detail, name='counselor_session_detail'),
    path('counselor/session/<int:session_id>/approve/', counselor_approve_session, name='counselor_approve_session'),
    path('counselor/session/<int:session_id>/reschedule/', counselor_reschedule_session, name='counselor_reschedule_session'),
    path('counselor/session/<int:session_id>/complete/', counselor_complete_session, name='counselor_complete_session'),
    path('counselor/session/<int:session_id>/update-title/', counselor_update_session_title, name='counselor_update_session_title'),
    path('counselor/session/<int:session_id>/reject/', counselor_reject_session, name='counselor_reject_session'),
    path('counselor/cases/', counselor_cases, name='counselor_cases'),
    path('counselor/case/<int:case_id>/', counselor_case_detail, name='counselor_case_detail'),
    path('counselor/case/<int:case_id>/link-session/', counselor_link_session_to_case, name='counselor_link_session_to_case'),
    path('counselor/case/create/', counselor_create_case, name='counselor_create_case'),
    path('counselor/students/', counselor_students, name='counselor_students'),
    path('counselor/student/<int:student_id>/', counselor_student_profile, name='counselor_student_profile'),
    path('counselor/calendar/', counselor_calendar, name='counselor_calendar'),
    path('calendar/events/', calendar_events, name='calendar_events'),
    path('counselor/reports/', counselor_reports, name='counselor_reports'),
    path('counselor/reports/export/<str:format>/', counselor_reports_export, name='counselor_reports_export'),
    path('counselor/settings/', counselor_settings, name='counselor_settings'),
    # Notification URLs
    path('notifications/', view_all_notifications, name='view_all_notifications'),
    path('notifications/<int:notif_id>/mark-read/', mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/check-new/', check_new_notifications, name='check_new_notifications'),
    
    # Session Creation
    path('counselor/session/create/', counselor_create_session, name='counselor_create_session'),
    
    # API Endpoints
    path('api/students/', api_get_students, name='api_get_students'),
    path('api/profiles/', api_get_profiles, name='api_get_profiles'),
    path('api/counselors/', api_get_counselors, name='api_get_counselors'),
    path('api/cases/active/', api_get_active_cases, name='api_get_active_cases'),
    
    # Hearing Management
    path('counselor/hearing/schedule/', counselor_schedule_hearing, name='counselor_schedule_hearing'),
    path('counselor/hearing/<int:hearing_id>/', counselor_hearing_detail, name='counselor_hearing_detail'),
    path('counselor/hearings/', counselor_hearings_list, name='counselor_hearings_list'),
    path('counselor/hearing/<int:hearing_id>/upload-evidence/', counselor_hearing_upload_evidence, name='counselor_hearing_upload_evidence'),
    path('counselor/hearing/<int:hearing_id>/post-decision/', counselor_hearing_post_decision, name='counselor_hearing_post_decision'),
]
