# Generated by Django 5.2.8 on 2026-01-28 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=10, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='N/A', max_length=20)),
                ('student_name', models.CharField(default='Not Specified', max_length=255)),
                ('student_email', models.EmailField(default='no-email@example.com', max_length=254)),
                ('student_year', models.CharField(default='Not Specified', max_length=20)),
                ('student_course', models.CharField(default='Not Specified', max_length=100)),
                ('student_section', models.CharField(default='Not Specified', max_length=20)),
                ('offense_type', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_details', models.TextField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('witnesses', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('academic', 'Academic Concerns'), ('personal', 'Personal Issues'), ('career', 'Career Planning'), ('mental_health', 'Mental Health Support'), ('other', 'Other')], max_length=20)),
                ('concern_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_session', to='app.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='sessions',
            field=models.ManyToManyField(related_name='cases', to='app.guidancesession'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('counselor', 'Counselor')], default='student', max_length=10)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('counselor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('year_level', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='assigned_counselor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='app.profile'),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='preferred_counselor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'counselor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_sessions', to='app.profile'),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.profile'),
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('report_data', models.JSONField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='counselor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to='app.profile'),
        ),
        migrations.AddField(
            model_name='case',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.profile'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=10)),
                ('counselor', models.ForeignKey(limit_choices_to={'user_type': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_assigned', to='app.profile')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_for_session', models.CharField(choices=[('tardiness', 'Tardiness'), ('absence', 'Unexcused Absence'), ('misconduct', 'Academic Misconduct'), ('disruption', 'Classroom Disruption'), ('bullying', 'Bullying/Harassment'), ('violation', 'Code of Conduct Violation'), ('substance', 'Substance-related Issue'), ('other', 'Other')], max_length=20)),
                ('hearing_frequency', models.CharField(choices=[('1st', '1st Hearing'), ('2nd', '2nd Hearing'), ('3rd', '3rd Hearing'), ('4th', '4th Hearing (Final)')], max_length=3)),
                ('detailed_assessment', models.TextField()),
                ('severity_level', models.CharField(choices=[('minor', 'Minor Offense'), ('major', 'Major Offense'), ('severe', 'Severe Offense')], max_length=10)),
                ('follow_up_required', models.CharField(choices=[('none', 'No Follow-up Needed'), ('monitoring', 'Behavioral Monitoring'), ('counseling', 'Additional Counseling'), ('parent', 'Parent Conference'), ('disciplinary', 'Disciplinary Action')], default='none', max_length=15)),
                ('is_draft', models.BooleanField(default=False)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_evaluations', to='app.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
