# Generated by Django 5.2.8 on 2026-01-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guidancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
