# Generated by Django 5.2.8 on 2026-01-30 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_case_is_active_guidancesession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
