# Generated by Django 5.2.8 on 2026-01-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailverification_created_at_emailverification_email'),
    ]

    operations = [
    ]
