# Generated by Django 5.2.8 on 2026-01-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20260130_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_request', 'Session Request'), ('session_approved', 'Session Approved'), ('session_scheduled', 'Session Scheduled'), ('session_completed', 'Session Completed'), ('session_cancelled', 'Session Cancelled'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_assigned', 'Case Assigned'), ('case_resolved', 'Case Resolved'), ('comment_added', 'Comment Added'), ('reminder', 'Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
