# Generated by Django 5.2.8 on 2026-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
