# Generated by Django 5.2.8 on 2026-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_guidancesession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesession',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Additional participants in this session (parents, other students, etc.)', related_name='participated_sessions', to='app.profile'),
        ),
    ]
