# Generated by Django 5.2.8 on 2026-02-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_guidancesession_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_number', models.CharField(help_text='Unique identifier (e.g., H-2024-001)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('hearing_type', models.CharField(choices=[('disciplinary', 'Disciplinary Hearing'), ('appeal', 'Appeal Hearing'), ('resolution', 'Resolution Meeting'), ('investigation', 'Investigation Hearing'), ('review', 'Case Review Hearing')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('estimated_duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('location', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online/Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=15)),
                ('meeting_link', models.URLField(blank=True, help_text='Link for online hearings', null=True)),
                ('agenda', models.TextField(help_text='Hearing agenda/outline')),
                ('charges', models.TextField(blank=True, help_text='Formal charges or allegations')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('guilty', 'Guilty/Responsible'), ('not_guilty', 'Not Guilty/Not Responsible'), ('dismissed', 'Dismissed'), ('referred', 'Referred to Another Body')], default='pending', max_length=20)),
                ('decision', models.TextField(blank=True, help_text='Formal decision and reasoning')),
                ('sanctions', models.JSONField(blank=True, default=list, help_text='List of sanctions/consequences imposed')),
                ('minutes', models.TextField(blank=True, help_text='Official minutes of the hearing')),
                ('minutes_finalized', models.BooleanField(default=False)),
                ('appeal_deadline', models.DateField(blank=True, null=True)),
                ('appeal_filed', models.BooleanField(default=False)),
                ('appeal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisors', models.ManyToManyField(blank=True, help_text='Advisors (parents, guardians, support persons)', related_name='hearings_advisor', to='app.profile')),
                ('case', models.ForeignKey(help_text='The case this hearing is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='app.case')),
                ('complainant', models.ForeignKey(blank=True, help_text='Person filing complaint (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings_complainant', to='app.profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings_created', to='app.profile')),
                ('panel_members', models.ManyToManyField(blank=True, help_text='Panel members/committee', related_name='hearings_panel', to='app.profile')),
                ('presiding_officer', models.ForeignKey(help_text='Person conducting the hearing', on_delete=django.db.models.deletion.PROTECT, related_name='hearings_presided', to='app.profile')),
                ('respondent', models.ForeignKey(help_text='Student or person being heard', on_delete=django.db.models.deletion.CASCADE, related_name='hearings_respondent', to='app.profile')),
                ('witnesses', models.ManyToManyField(blank=True, help_text='Witnesses to be called', related_name='hearings_witness', to='app.profile')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='HearingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('presiding_officer', 'Presiding Officer'), ('panel_member', 'Panel Member'), ('respondent', 'Respondent'), ('complainant', 'Complainant'), ('witness', 'Witness'), ('advisor', 'Advisor'), ('observer', 'Observer')], max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('absent', 'Absent'), ('excused', 'Excused')], default='invited', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='app.hearing')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'ordering': ['role', 'participant'],
            },
        ),
        migrations.CreateModel(
            name='HearingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo/Image'), ('video', 'Video'), ('audio', 'Audio Recording'), ('testimony', 'Written Testimony'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='hearings/evidence/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='app.hearing')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_submitted', to='app.profile')),
            ],
            options={
                'verbose_name_plural': 'Hearing evidence',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_entries', to='app.hearing')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile')),
            ],
            options={
                'verbose_name_plural': 'Hearing minutes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['hearing_number'], name='app_hearing_hearing_f56d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['scheduled_date'], name='app_hearing_schedul_53c104_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['status'], name='app_hearing_status_a0198b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hearingattendance',
            unique_together={('hearing', 'participant', 'role')},
        ),
    ]
